sudo: false

language: scala

scala:
  - 2.13.0-M5

jdk: oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_script:
- git clone -b v0.9.7 https://github.com/non/kind-projector.git
- cd kind-projector
- sbt "++ ${TRAVIS_SCALA_VERSION}!" publishLocal
- cd ..
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" compile
