language: scala

scala:
  - 2.10.4
  - 2.11.0

jdk:
  - oraclejdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean specs2-common/update specs2-common/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean specs2-common/update specs2-common/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean specs2-common/update specs2-common/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean specs2-common/update specs2-common/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean specs2-common/update specs2-common/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean specs2-common/update specs2-common/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean specs2-common/update specs2-common/compile
